version: "3"
services:
  minesweaper-app:
    image: jungrt/sample-app
    container_name: minesweaper-app
    working_dir: /usr/src/app
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ~/.ssh:/root/.ssh
      - "./:/usr/src/app:cached"
